---
title: Stackbit Exto Theme
baseURL: "/"
params:
  color_scheme: light
  accent_color: pink
  header:
    title: Tuna Universit√°ria do Minho
    has_nav: true
  footer:
    content: "&copy; Stackbit-Exto. All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
    has_social: true
disableKinds:
- RSS
taxonomies:
  category: categories
  tag: tags
